### ISSUE TITLE
After updating the DAS Keyboard X50Q to FW v57.0.0, LED lights stop working completely.

### ISSUE THREAD

**Issue by Cxpher** [daskeyboard/daskeyboard.io#57]
From URL: https://www.daskeyboard.io/get-started/firmware.md

After updating the X50Q to v57.0.0 in Windows, when plugging it back into Linux, none of the LEDs except numlock light up.

Attempting to switch to color profiles using NUM 1-6 don't work at all. Fn+12 works for NKRO but that's about it.

Without the software available as well, it's basically impossible to get any form of lights to show up.

**Comment by Cxpher** [comment]
Once i downgraded the firmware from 0039 (Provided by 57.0.0) to 0037, the issues were resolved. 

There's still no proper color profile switching built in like the 5Q but hey, at least lights are back. 

Another issue i had with 0039 was that within a day of flashing it, all buttons started to automatically map to FN key which brought up the Windows Start Menu. Weird. Resolved once i downgraded as well.

**Comment by jester187** [comment]
Cxpher you still have the old firmware? i upgraded to the newest firmware and have a lot of problems/ bugs now.

Can't find the old firmware anywhere.
